name: Automatic Versioning

on:
  workflow_run:
    workflows: ['Check for Changesets']
    types:
      - completed

jobs:
  version:
    if: github.event.workflow_run.conclusion == 'success' # Only run the job if "Check for Changesets" workflow was successful
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Fetch latest from main and reset local main branch
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Version Packages
        run: npx changeset version

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and Push Changes
        run: |
          git add -A
          if [ -z "$(git diff --cached --exit-code)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Version packages and update changelog [skip ci]"
          git push origin main
